In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import streamlit as stl
import re

In [2]:
pd.set_option('display.max_column' ,None)
pd.set_option('display.max_row' ,None)
data = pd.read_csv('Drug_overdose_death_rates__by_drug_type__sex__age__race__and_Hispanic_origin__United_States.csv')

In [137]:
pd.set_option('display.max_column' ,None)
pd.set_option('display.max_row' ,None)
data2 = pd.read_csv('Drug_overdose_death_rates__by_drug_type__sex__age__race__and_Hispanic_origin__United_States.csv')
data2.tail(20)

,INDICATOR,PANEL,PANEL_NUM,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,STUB_LABEL,STUB_LABEL_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG
6208,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex,2,Male,2.10,2018,20,All ages,1.10,7.0,NaN
6209,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex,2,Female,2.20,2018,20,All ages,1.10,2.2,NaN
6210,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: Under 15 years,3.11,2018,20,Under 15 years,1.20,NaN,*
6211,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 15-24 years,3.12,2018,20,15-24 years,1.30,3.7,NaN
6212,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 25-34 years,3.13,2018,20,25-34 years,1.40,15.0,NaN
6213,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 35-44 years,3.14,2018,20,35-44 years,1.50,13.7,NaN
6214,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 45-54 years,3.15,2018,20,45-54 years,1.60,10.7,NaN
6215,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 55-64 years,3.16,2018,20,55-64 years,1.70,7.7,NaN
6216,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 65-74 years,3.17,2018,20,65-74 years,1.80,2.6,NaN
6217,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 75-84 years,3.18,2018,20,75-84 years,1.90,NaN,*
6218,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Male: 85 years and over,3.19,2018,20,85 years and over,1.91,NaN,*
6219,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: Under 15 years,3.21,2018,20,Under 15 years,1.20,NaN,*
6220,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 15-24 years,3.22,2018,20,15-24 years,1.30,1.6,NaN
6221,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 25-34 years,3.23,2018,20,25-34 years,1.40,5.2,NaN
6222,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 35-44 years,3.24,2018,20,35-44 years,1.50,4.4,NaN
6223,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 45-54 years,3.25,2018,20,45-54 years,1.60,3.4,NaN
6224,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 55-64 years,3.26,2018,20,55-64 years,1.70,2.3,NaN
6225,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 65-74 years,3.27,2018,20,65-74 years,1.80,0.4,NaN
6226,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 75-84 years,3.28,2018,20,75-84 years,1.90,NaN,*
6227,Drug overdose death rates,Drug overdose deaths involving heroin,5,"Deaths per 100,000 resident population, crude",2,Sex and age,3,Female: 85 years and over,3.29,2018,20,85 years and over,1.91,NaN,*

In [ ]:
data.head(15)

,ID,INDICATOR,PANEL,PANEL_NUM,UNIT,UNIT_NUM,STUB_NAME,STUB_NAME_NUM,YEAR,YEAR_NUM,AGE,AGE_NUM,ESTIMATE,FLAG,GENDER,RACE,AGE-GROUP
0,ID001,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,1999,1,All ages,1,6.1,No Notice,Any,Undefined,Undefined
1,ID002,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2000,2,All ages,1,6.2,No Notice,Any,Undefined,Undefined
2,ID003,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2001,3,All ages,1,6.8,No Notice,Any,Undefined,Undefined
3,ID004,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2002,4,All ages,1,8.2,No Notice,Any,Undefined,Undefined
4,ID005,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2003,5,All ages,1,8.9,No Notice,Any,Undefined,Undefined
5,ID006,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2004,6,All ages,1,9.4,No Notice,Any,Undefined,Undefined
6,ID007,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2005,7,All ages,1,10.1,No Notice,Any,Undefined,Undefined
7,ID008,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2006,8,All ages,1,11.5,No Notice,Any,Undefined,Undefined
8,ID009,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2007,9,All ages,1,11.9,No Notice,Any,Undefined,Undefined
9,ID010,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2008,10,All ages,1,11.9,No Notice,Any,Undefined,Undefined
10,ID011,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2009,11,All ages,1,11.9,No Notice,Any,Undefined,Undefined
11,ID012,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2010,12,All ages,1,12.3,No Notice,Any,Undefined,Undefined
12,ID013,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2011,13,All ages,1,13.2,No Notice,Any,Undefined,Undefined
13,ID014,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2012,14,All ages,1,13.1,No Notice,Any,Undefined,Undefined
14,ID015,DODR,ADOD,1,DP100K/RP/AGE-ADJ,1,Total,1,2013,15,All ages,1,13.8,No Notice,Any,Undefined,Undefined

In [179]:
fig1 = px.box(data,x='STUB_NAME',y='RACE',color='STUB_NAME',template='plotly_dark')
fig1.show()

fig2 = px.line(data,x='PANEL',y='ESTIMATE',color='PANEL',template='plotly_dark')
fig2.show()

# fig3 = px
# fig3.show()

# fig4 = px
# fig4.show()

# fig5 = px
# fig5.show()

# fig6 = px
# fig6.show()

# fig7 = px
# fig7.show()

# fig8 = px
# fig8.show()

# fig9 = px
# fig9.show()

# fig10 = px
# fig10.show()

In [9]:
# data.describe()
# data.info()
# data.shape
# data.groupby(['INDICATOR'])['PANEL'].value_counts()
# data['AGE_NUM'].value_counts()
# data['YEAR_NUM'].value_counts()
# data['STUB_LABEL'].value_counts()
# data['GENDER'].isnull().value_counts()
# data['STUB_NAME'].value_counts()
# data.columns
# data[['YEAR','YEAR_NUM']].drop_duplicates().sort_values('YEAR')
# data[['PANEL','PANEL_NUM']].drop_duplicates().sort_values('PANEL')
# data[['AGE','AGE_NUM']].drop_duplicates().sort_values('AGE')
# data[['RACE','STUB_LABEL_NUM']].drop_duplicates().sort_values('RACE')
# data2[['STUB_LABEL','STUB_LABEL_NUM']].drop_duplicates().sort_values('STUB_LABEL')

# data['RACE'].isnull().sum()
# data['ESTIMATE'].isnull().sum()

# df = data[['RACE','STUB_LABEL_NUM']].drop_duplicates().sort_values('RACE')
# df.sort_values(by='STUB_LABEL_NUM', inplace=True)
# df

# df = data[['STUB_NAME','STUB_NAME_NUM']].drop_duplicates().sort_values('STUB_NAME')
# df.sort_values(by='STUB_NAME_NUM', inplace=True)
# df

# data['FLAG'].value_counts()
# data['AGE-GROUP'].value_counts()
# data['RACE'].value_counts()
# data['GENDER'].value_counts()
# data['PANEL'].value_counts()
# data['STUB_NAME_NUM'].value_counts()
# data['UNIT_NUM'].value_counts()
# data['STUB_NAME'].value_counts()

data.dtypes
# data['ESTIMATE'] = data['ESTIMATE'].astype(float)

ID               object
INDICATOR        object
PANEL            object
PANEL_NUM         int64
UNIT             object
UNIT_NUM          int64
STUB_NAME        object
STUB_NAME_NUM     int64
YEAR              int64
YEAR_NUM          int64
AGE              object
AGE_NUM           int64
ESTIMATE         object
FLAG             object
GENDER           object
RACE             object
AGE-GROUP        object
dtype: object

In [ ]:
data.insert(0, 'ID',[f'ID{i:03d}' for i in range(1, len(data)+1)]) 

#------------------------------------------------------------

data['INDICATOR'] = data['INDICATOR'].replace('Drug overdose death rates','DODR')

data['PANEL'] = data['PANEL'].replace('All drug overdose deaths','ADOD')
data['PANEL'] = data['PANEL'].replace('Drug overdose deaths involving any opioid','DODIO')
data['PANEL'] = data['PANEL'].replace('Drug overdose deaths involving heroin','DODIH')
data['PANEL'] = data['PANEL'].replace('Drug overdose deaths involving methadone','DODIM')
data['PANEL'] = data['PANEL'].replace('Drug overdose deaths involving natural and semisynthetic opioids','DODINSO')
data['PANEL'] = data['PANEL'].replace('Drug overdose deaths involving other synthetic opioids (other than methadone)','DODISO ! OTM')

data['STUB_NAME'] = data['STUB_NAME'].str.replace('and','&',regex = False)
data['STUB_NAME'] = data['STUB_NAME'].str.replace('race','Race',regex = False)
data['STUB_NAME'] = data['STUB_NAME'].str.replace('age','Age',regex = False)
data['STUB_NAME'] = data['STUB_NAME'].str.replace('Hispanic origin','H-Origin',regex = False)
data['STUB_NAME'] = data['STUB_NAME'].str.replace('(single Race)','(Single Race)',regex = False)

data['FLAG'] = data['FLAG'].replace('*','Unstable')
data['FLAG'] = data['FLAG'].fillna('No Notice')

data['PANEL_NUM'] = data['PANEL_NUM']+1

data['STUB_NAME_NUM'] = data['STUB_NAME_NUM']+1

data['UNIT'] = data['UNIT'].replace('Deaths per 100,000 resident population, crude','DP100K/RP/CRD')
data['UNIT'] = data['UNIT'].replace('Deaths per 100,000 resident population, age-adjusted','DP100K/RP/AGE-ADJ')

#------------------------------------------------------------

data['GENDER'] = data['STUB_LABEL'].str.extract('(Male|Female|All persons)' , expand = False)
data['RACE'] = data['STUB_LABEL'].str.extract('(White|Black or African American|Hispanic or Latino: All races|American Indian or Alaska Native|Not Hispanic or Latino: Black|Not Hispanic or Latino: White|Not Hispanic or Latino: American Indian or Alaska Native|Asian or Pacific Islander|Not Hispanic or Latino: Asian or Pacific Islander|Not Hispanic or Latino: Asian|Not Hispanic or Latino: Native Hawaiian or Other Pacific Islander)' , expand = False)

data['RACE'] = data['RACE'].str.replace('or','OR',regex = False)
data['RACE'] = data['RACE'].str.replace('African','Afro',regex = False)
data['RACE'] = data['RACE'].str.replace('Indian','Indi',regex = False)
data['RACE'] = data['RACE'].str.replace('Native','Nat',regex = False)
data['RACE'] = data['RACE'].str.replace('Hispanic','HIS',regex = False)
data['RACE'] = data['RACE'].str.replace('Latino','LAT',regex = False)
data['RACE'] = data['RACE'].str.replace('Hawaiian','HAWA',regex = False)
data['RACE'] = data['RACE'].str.replace('Pacific Islander','P-I',regex = False)
data['RACE'] = data['RACE'].str.replace('Other','~',regex = False)
data['RACE'] = data['RACE'].str.replace('Not HIS OR LAT:','',regex = False)

data['AGE-GROUP'] = data['STUB_LABEL'].str.extract('(Under 15|15-24|25-34|35-44|45-54|55-64|65-74|75-84|85 years and over)' , expand = False)

data['AGE-GROUP'] = data['AGE-GROUP'].replace('Under 15','Children')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('15-24','Youth')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('25-34','Young Adults')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('35-44','Adults')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('45-54','Middle-Aged')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('55-64','Pre-Seniors')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('65-74','Young Seniors')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('75-84','Seniors')
data['AGE-GROUP'] = data['AGE-GROUP'].replace('85 years and over','Oldest Seniors')
#------------------------------------------------------------

data['GENDER'] = data['GENDER'].replace('All persons','Any')

data['AGE-GROUP'] = data['AGE-GROUP'].fillna('Undefined')
data['ESTIMATE'] = data['ESTIMATE'].fillna('Undefined')
data['RACE'] = data['RACE'].fillna('Undefined')
data['GENDER'] = data['GENDER'].fillna('Any')


data['AGE_NUM'] = data['AGE_NUM'].replace({1.10:1,1.20:2,1.30:3,1.40:4,1.50:5,1.60:6,1.70:7,1.80:8,1.90:9,1.91:10}).astype(int)

#------------------------------------------------------------

data = data.drop(columns = ['STUB_LABEL','STUB_LABEL_NUM'])

In [4]:
data.to_excel('Drug_data_cleaned.xlsx', index=False)